# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoodosMovie' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LoodosMovie
  pod 'lottie-ios'
  pod 'Moya', '~> 15.0'
end
